// <auto-generated />
using System;
using FableCraft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FableCraft.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130221519_LogTable")]
    partial class LogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdventureStartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstSceneGuidance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RagProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SceneGenerationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackerStructure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Adventures");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterStats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Tracker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("SceneId");

                    b.HasIndex("SequenceNumber");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.LorebookEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("SceneId");

                    b.ToTable("LorebookEntries");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId")
                        .IsUnique();

                    b.ToTable("MainCharacter");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacterAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("CharacterActions");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdventureSummary")
                        .HasColumnType("text");

                    b.Property<string>("CommitStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NarrativeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId", "SequenceNumber");

                    b.HasIndex("Id", "SequenceNumber", "CommitStatus");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.TrackerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrackerDefinitions");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ContentHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("KnowledgeGraphNodeId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityId", "ContentHash")
                        .IsUnique();

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.GenerationProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GenerationProcesses");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.LlmLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("CallerName")
                        .HasColumnType("text");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<int?>("InputToken")
                        .HasColumnType("integer");

                    b.Property<int?>("OutputToken")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TotalToken")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.ToTable("LlmCallLogs");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Character", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", null)
                        .WithMany("Characters")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", null)
                        .WithMany("CharacterStates")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.LorebookEntry", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", "Adventure")
                        .WithMany("Lorebook")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany("Lorebooks")
                        .HasForeignKey("SceneId");

                    b.Navigation("Adventure");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacter", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", null)
                        .WithOne("MainCharacter")
                        .HasForeignKey("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacter", "AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacterAction", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany("CharacterActions")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", "Adventure")
                        .WithMany("Scenes")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adventure");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Lorebook");

                    b.Navigation("MainCharacter")
                        .IsRequired();

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", b =>
                {
                    b.Navigation("CharacterActions");

                    b.Navigation("CharacterStates");

                    b.Navigation("Lorebooks");
                });
#pragma warning restore 612, 618
        }
    }
}
