// <auto-generated />
using System;
using FableCraft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FableCraft.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260131100627_AddWorldbookSettings")]
    partial class AddWorldbookSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdventureStartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstSceneGuidance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GraphRagSettingsId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PromptPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RagProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SceneGenerationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackerStructure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorldbookId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GraphRagSettingsId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Adventures");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.AdventureAgentLlmPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LlmPresetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LlmPresetId");

                    b.HasIndex("AdventureId", "AgentName")
                        .IsUnique();

                    b.ToTable("AdventureAgentLlmPresets");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.BackgroundCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ConvertedToFull")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSeenTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("BackgroundCharacters");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("IntroductionScene")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("SceneId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.CharacterEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceCharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRead")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetCharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CharacterEvents");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.CharacterMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<double>("Salience")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<string>("SceneTracker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SceneId");

                    b.HasIndex("CharacterId", "Salience");

                    b.ToTable("CharacterMemories");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.CharacterRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dynamic")
                        .HasColumnType("text");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TargetCharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdateTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("CharacterId", "TargetCharacterName", "SequenceNumber");

                    b.ToTable("CharacterRelationships");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.CharacterSceneRewrite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<string>("SceneTracker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("CharacterId", "SequenceNumber");

                    b.ToTable("CharacterSceneRewrites");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.CharacterState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterStats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SimulationMetadata")
                        .HasColumnType("text");

                    b.Property<string>("Tracker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("CharacterId", "SequenceNumber", "IsDead")
                        .IsUnique();

                    b.ToTable("CharacterStates");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.LorebookEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("SceneId");

                    b.ToTable("LorebookEntries");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId")
                        .IsUnique();

                    b.ToTable("MainCharacters");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacterAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("CharacterActions");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdventureSummary")
                        .HasColumnType("text");

                    b.Property<string>("CommitStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnrichmentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NarrativeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("Id", "SequenceNumber", "CommitStatus");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.TrackerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrackerDefinitions");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ContentHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("KnowledgeGraphNodeId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityId", "ContentHash", "DatasetName")
                        .IsUnique();

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.GenerationProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GenerationProcesses");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.GraphRagSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EmbeddingApiVersion")
                        .HasColumnType("text");

                    b.Property<int>("EmbeddingBatchSize")
                        .HasColumnType("integer");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EmbeddingMaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HuggingfaceTokenizer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LlmApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LlmApiVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LlmEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LlmMaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LlmRateLimitEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("LlmRateLimitInterval")
                        .HasColumnType("integer");

                    b.Property<int>("LlmRateLimitRequests")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GraphRagSettings");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.LlmLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("CallerName")
                        .HasColumnType("text");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<int?>("InputToken")
                        .HasColumnType("integer");

                    b.Property<int?>("OutputToken")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TotalToken")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("SceneId");

                    b.ToTable("LlmCallLogs");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.LlmPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("FrequencyPenalty")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("PresencePenalty")
                        .HasColumnType("double precision");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<int?>("TopK")
                        .HasColumnType("integer");

                    b.Property<double?>("TopP")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmPresets");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Lorebook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorldbookId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldbookId", "Title")
                        .IsUnique();

                    b.ToTable("Lorebooks");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Worldbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GraphRagSettingsId")
                        .HasColumnType("uuid");

                    b.Property<string>("IndexingError")
                        .HasColumnType("text");

                    b.Property<int>("IndexingStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GraphRagSettingsId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Worldbooks");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.GraphRagSettings", "GraphRagSettings")
                        .WithMany("Adventures")
                        .HasForeignKey("GraphRagSettingsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GraphRagSettings");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.AdventureAgentLlmPreset", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", "Adventure")
                        .WithMany("AgentLlmPresets")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.LlmPreset", "LlmPreset")
                        .WithMany()
                        .HasForeignKey("LlmPresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adventure");

                    b.Navigation("LlmPreset");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.BackgroundCharacter", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Character", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", null)
                        .WithMany("Characters")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.CharacterMemory", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Character", null)
                        .WithMany("CharacterMemories")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany("CharacterMemories")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.CharacterRelationship", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Character", null)
                        .WithMany("CharacterRelationships")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany("CharacterRelationships")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.CharacterSceneRewrite", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Character", null)
                        .WithMany("CharacterSceneRewrites")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany("CharacterSceneRewrites")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.CharacterState", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Character", null)
                        .WithMany("CharacterStates")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany("CharacterStates")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.LorebookEntry", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", "Adventure")
                        .WithMany("Lorebook")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany("Lorebooks")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Adventure");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacter", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", null)
                        .WithOne("MainCharacter")
                        .HasForeignKey("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacter", "AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.MainCharacterAction", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", "Scene")
                        .WithMany("CharacterActions")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", "Adventure")
                        .WithMany("Scenes")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adventure");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Lorebook", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Worldbook", "Worldbook")
                        .WithMany("Lorebooks")
                        .HasForeignKey("WorldbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worldbook");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Worldbook", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.GraphRagSettings", "GraphRagSettings")
                        .WithMany("Worldbooks")
                        .HasForeignKey("GraphRagSettingsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GraphRagSettings");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Adventure", b =>
                {
                    b.Navigation("AgentLlmPresets");

                    b.Navigation("Characters");

                    b.Navigation("Lorebook");

                    b.Navigation("MainCharacter")
                        .IsRequired();

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Character", b =>
                {
                    b.Navigation("CharacterMemories");

                    b.Navigation("CharacterRelationships");

                    b.Navigation("CharacterSceneRewrites");

                    b.Navigation("CharacterStates");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure.Scene", b =>
                {
                    b.Navigation("CharacterActions");

                    b.Navigation("CharacterMemories");

                    b.Navigation("CharacterRelationships");

                    b.Navigation("CharacterSceneRewrites");

                    b.Navigation("CharacterStates");

                    b.Navigation("Lorebooks");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.GraphRagSettings", b =>
                {
                    b.Navigation("Adventures");

                    b.Navigation("Worldbooks");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Worldbook", b =>
                {
                    b.Navigation("Lorebooks");
                });
#pragma warning restore 612, 618
        }
    }
}
