// <auto-generated />
using System;
using System.Collections.Generic;
using FableCraft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FableCraft.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdventureStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstSceneGuidance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackerStructure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Adventures");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("Name");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.CharacterState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Tracker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CharacterStats", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "BehavioralState", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.BehavioralState#BehavioralState", b2 =>
                                {
                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "ActionTendencies", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.BehavioralState#BehavioralState.ActionTendencies#ActionTendencies", b3 =>
                                        {
                                            b3.Property<string>("DefaultResponseToAggression")
                                                .HasJsonPropertyName("default_response_to_aggression");

                                            b3.Property<string>("ResponseToDeception")
                                                .HasJsonPropertyName("response_to_deception");

                                            b3.Property<string>("ResponseToKindness")
                                                .HasJsonPropertyName("response_to_kindness");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Availability", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.BehavioralState#BehavioralState.Availability#Availability", b3 =>
                                        {
                                            b3.PrimitiveCollection<string>("ConditionsForEncounter")
                                                .HasJsonPropertyName("conditions_for_encounter");

                                            b3.Property<string>("CurrentLocation")
                                                .HasJsonPropertyName("current_location");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "CurrentPlan", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.BehavioralState#BehavioralState.CurrentPlan#CurrentPlan", b3 =>
                                        {
                                            b3.Property<Dictionary<string, string>>("ContingencyPlans")
                                                .HasJsonPropertyName("contingency_plans");

                                            b3.Property<string>("ExpectedDurationScenes")
                                                .IsRequired()
                                                .HasJsonPropertyName("expected_duration_scenes");

                                            b3.Property<string>("Intention")
                                                .HasJsonPropertyName("intention");

                                            b3.PrimitiveCollection<string>("Steps")
                                                .HasJsonPropertyName("steps");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CharacterArc", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.CharacterArc#CharacterArc", b2 =>
                                {
                                    b2.Property<string>("ArcType")
                                        .HasJsonPropertyName("arc_type");

                                    b2.Property<string>("CurrentStage")
                                        .HasJsonPropertyName("current_stage");

                                    b2.Property<string>("Description")
                                        .HasJsonPropertyName("description");

                                    b2.PrimitiveCollection<string>("KeyDecisionsPending")
                                        .HasJsonPropertyName("key_decisions_pending");

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "ArcStages", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.CharacterArc#CharacterArc.ArcStages#ArcStage", b3 =>
                                        {
                                            b3.Property<bool>("Completed")
                                                .HasJsonPropertyName("completed");

                                            b3.Property<string>("Description")
                                                .HasJsonPropertyName("description");

                                            b3.PrimitiveCollection<string>("KeyEvents")
                                                .HasJsonPropertyName("key_events");

                                            b3.Property<int?>("ProgressPercentage")
                                                .HasJsonPropertyName("progress_percentage");

                                            b3.Property<string>("StageName")
                                                .HasJsonPropertyName("stage_name");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CharacterIdentity", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.CharacterIdentity#CharacterIdentity", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.PrimitiveCollection<string>("Aliases")
                                        .HasJsonPropertyName("aliases");

                                    b2.Property<string>("Archetype")
                                        .HasJsonPropertyName("archetype");

                                    b2.Property<string>("FullName")
                                        .HasJsonPropertyName("full_name");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "EmotionalState", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.EmotionalState#EmotionalState", b2 =>
                                {
                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "CurrentEmotions", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.EmotionalState#EmotionalState.CurrentEmotions#CurrentEmotions", b3 =>
                                        {
                                            b3.Property<double>("Intensity")
                                                .HasJsonPropertyName("intensity");

                                            b3.Property<string>("PrimaryEmotion")
                                                .HasJsonPropertyName("primary_emotion");

                                            b3.PrimitiveCollection<string>("SecondaryEmotions")
                                                .HasJsonPropertyName("secondary_emotions");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "EmotionalTriggers", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.EmotionalState#EmotionalState.EmotionalTriggers#EmotionalTriggers", b3 =>
                                        {
                                            b3.PrimitiveCollection<string>("Negative")
                                                .HasJsonPropertyName("negative");

                                            b3.PrimitiveCollection<string>("Positive")
                                                .HasJsonPropertyName("positive");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "GoalsAndMotivations", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.GoalsAndMotivations#GoalsAndMotivations", b2 =>
                                {
                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Motivations", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.GoalsAndMotivations#GoalsAndMotivations.Motivations#Motivations", b3 =>
                                        {
                                            b3.PrimitiveCollection<string>("Extrinsic")
                                                .HasJsonPropertyName("extrinsic");

                                            b3.PrimitiveCollection<string>("Intrinsic")
                                                .HasJsonPropertyName("intrinsic");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "PrimaryGoal", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.GoalsAndMotivations#GoalsAndMotivations.PrimaryGoal#PrimaryGoal", b3 =>
                                        {
                                            b3.Property<string>("Description")
                                                .HasJsonPropertyName("description");

                                            b3.PrimitiveCollection<string>("FailureConditions")
                                                .HasJsonPropertyName("failure_conditions");

                                            b3.Property<string>("GoalType")
                                                .HasJsonPropertyName("goal_type");

                                            b3.Property<int>("Priority")
                                                .HasJsonPropertyName("priority");

                                            b3.Property<int>("ProgressPercentage")
                                                .HasJsonPropertyName("progress_percentage");

                                            b3.PrimitiveCollection<string>("SuccessConditions")
                                                .HasJsonPropertyName("success_conditions");

                                            b3.Property<string>("TimeSensitivity")
                                                .HasJsonPropertyName("time_sensitivity");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "SecondaryGoals", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.GoalsAndMotivations#GoalsAndMotivations.SecondaryGoals#SecondaryGoal", b3 =>
                                        {
                                            b3.Property<string>("Description")
                                                .HasJsonPropertyName("description");

                                            b3.Property<string>("GoalType")
                                                .HasJsonPropertyName("goal_type");

                                            b3.PrimitiveCollection<string>("Prerequisites")
                                                .HasJsonPropertyName("prerequisites");

                                            b3.Property<int>("Priority")
                                                .HasJsonPropertyName("priority");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Integration", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Integration#Integration", b2 =>
                                {
                                    b2.Property<string>("CulturalBackground")
                                        .HasJsonPropertyName("cultural_background");

                                    b2.PrimitiveCollection<string>("LocationKnowledge")
                                        .HasJsonPropertyName("location_knowledge");

                                    b2.PrimitiveCollection<string>("RecentEventsAwareOf")
                                        .HasJsonPropertyName("recent_events_aware_of");

                                    b2.PrimitiveCollection<string>("RelevantLore")
                                        .HasJsonPropertyName("relevant_lore");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "KnowledgeAndBeliefs", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.KnowledgeAndBeliefs#KnowledgeAndBeliefs", b2 =>
                                {
                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "BeliefsAboutProtagonist", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.KnowledgeAndBeliefs#KnowledgeAndBeliefs.BeliefsAboutProtagonist#BeliefAboutProtagonist", b3 =>
                                        {
                                            b3.Property<string>("Belief")
                                                .HasJsonPropertyName("belief");

                                            b3.Property<double>("ConfidenceLevel")
                                                .HasJsonPropertyName("confidence_level");

                                            b3.PrimitiveCollection<string>("Evidence")
                                                .HasJsonPropertyName("evidence");

                                            b3.Property<string>("FormedAtScene")
                                                .HasJsonPropertyName("formed_at_scene");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "SecretsHeld", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.KnowledgeAndBeliefs#KnowledgeAndBeliefs.SecretsHeld#Secret", b3 =>
                                        {
                                            b3.PrimitiveCollection<string>("RevealConditions")
                                                .HasJsonPropertyName("reveal_conditions");

                                            b3.Property<string>("SecretContent")
                                                .HasJsonPropertyName("secret_content");

                                            b3.Property<double>("WillingnessToShare")
                                                .HasJsonPropertyName("willingness_to_share");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "WorldKnowledge", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.KnowledgeAndBeliefs#KnowledgeAndBeliefs.WorldKnowledge#WorldKnowledge", b3 =>
                                        {
                                            b3.Property<double>("ConfidenceLevel")
                                                .HasJsonPropertyName("confidence_level");

                                            b3.Property<string>("Fact")
                                                .HasJsonPropertyName("fact");

                                            b3.Property<string>("KgReference")
                                                .HasJsonPropertyName("kg_reference");

                                            b3.Property<string>("LearnedAtScene")
                                                .HasJsonPropertyName("learned_at_scene");

                                            b3.Property<string>("Source")
                                                .HasJsonPropertyName("source");
                                        });
                                });

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "MemoryStream", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.MemoryStream#MemoryEntry", b2 =>
                                {
                                    b2.Property<string>("Description")
                                        .HasJsonPropertyName("description");

                                    b2.Property<string>("EmotionalValence")
                                        .HasJsonPropertyName("emotional_valence");

                                    b2.Property<string>("EventReference")
                                        .HasJsonPropertyName("event_reference");

                                    b2.Property<string>("MemoryType")
                                        .HasJsonPropertyName("memory_type");

                                    b2.PrimitiveCollection<string>("Outcomes")
                                        .HasJsonPropertyName("outcomes");

                                    b2.PrimitiveCollection<string>("Participants")
                                        .HasJsonPropertyName("participants");

                                    b2.Property<string>("SceneReference")
                                        .HasJsonPropertyName("scene_reference");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Personality", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Personality#Personality", b2 =>
                                {
                                    b2.PrimitiveCollection<string>("CoreTraits")
                                        .HasJsonPropertyName("core_traits");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "FiveFactorModel", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Personality#Personality.FiveFactorModel#FiveFactorModel", b3 =>
                                        {
                                            b3.Property<double>("Agreeableness")
                                                .HasJsonPropertyName("agreeableness");

                                            b3.Property<double>("Conscientiousness")
                                                .HasJsonPropertyName("conscientiousness");

                                            b3.Property<double>("Extraversion")
                                                .HasJsonPropertyName("extraversion");

                                            b3.Property<double>("Neuroticism")
                                                .HasJsonPropertyName("neuroticism");

                                            b3.Property<double>("Openness")
                                                .HasJsonPropertyName("openness");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "MoralAlignment", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Personality#Personality.MoralAlignment#MoralAlignment", b3 =>
                                        {
                                            b3.Property<double>("GoodEvilAxis")
                                                .HasJsonPropertyName("good_evil_axis");

                                            b3.Property<double>("LawfulChaoticAxis")
                                                .HasJsonPropertyName("lawful_chaotic_axis");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "SpeechPatterns", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Personality#Personality.SpeechPatterns#SpeechPatterns", b3 =>
                                        {
                                            b3.Property<string>("AccentOrDialect")
                                                .HasJsonPropertyName("accent_or_dialect");

                                            b3.Property<string>("FormalityLevel")
                                                .HasJsonPropertyName("formality_level");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Relationships", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Relationships#Relationships", b2 =>
                                {
                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "FactionAffiliations", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Relationships#Relationships.FactionAffiliations#FactionAffiliation", b3 =>
                                        {
                                            b3.Property<string>("FactionName")
                                                .HasJsonPropertyName("faction_name");

                                            b3.Property<string>("RankOrRole")
                                                .HasJsonPropertyName("rank_or_role");

                                            b3.Property<int>("Standing")
                                                .HasJsonPropertyName("standing");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "WithOtherCharacters", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Relationships#Relationships.WithOtherCharacters#RelationshipWithOther", b3 =>
                                        {
                                            b3.Property<string>("CharacterReference")
                                                .HasJsonPropertyName("character_reference");

                                            b3.Property<string>("ConflictReason")
                                                .HasJsonPropertyName("conflict_reason");

                                            b3.Property<string>("CurrentStatus")
                                                .HasJsonPropertyName("current_status");

                                            b3.Property<string>("Description")
                                                .HasJsonPropertyName("description");

                                            b3.Property<string>("RelationshipType")
                                                .HasJsonPropertyName("relationship_type");

                                            b3.Property<int>("TrustLevel")
                                                .HasJsonPropertyName("trust_level");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "WithProtagonist", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Relationships#Relationships.WithProtagonist#RelationshipWithProtagonist", b3 =>
                                        {
                                            b3.Property<int>("AffectionLevel")
                                                .HasJsonPropertyName("affection_level");

                                            b3.Property<string>("FirstMetScene")
                                                .HasJsonPropertyName("first_met_scene");

                                            b3.PrimitiveCollection<string>("RelationshipTags")
                                                .HasJsonPropertyName("relationship_tags");

                                            b3.Property<string>("RelationshipType")
                                                .HasJsonPropertyName("relationship_type");

                                            b3.Property<string>("ReputationInfluence")
                                                .HasJsonPropertyName("reputation_influence");

                                            b3.Property<int>("RespectLevel")
                                                .HasJsonPropertyName("respect_level");

                                            b3.Property<int>("TrustLevel")
                                                .HasJsonPropertyName("trust_level");

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "DebtsAndObligations", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Relationships#Relationships.WithProtagonist#RelationshipWithProtagonist.DebtsAndObligations#DebtAndObligation", b4 =>
                                                {
                                                    b4.Property<string>("Description")
                                                        .HasJsonPropertyName("description");

                                                    b4.Property<string>("Direction")
                                                        .HasJsonPropertyName("direction");

                                                    b4.Property<string>("Magnitude")
                                                        .HasJsonPropertyName("magnitude");

                                                    b4.Property<string>("OriginEvent")
                                                        .HasJsonPropertyName("origin_event");

                                                    b4.Property<string>("Status")
                                                        .HasJsonPropertyName("status");

                                                    b4.Property<string>("TermsOfRepayment")
                                                        .HasJsonPropertyName("terms_of_repayment");

                                                    b4.Property<string>("Type")
                                                        .HasJsonPropertyName("type");

                                                    b4.Property<string>("Urgency")
                                                        .HasJsonPropertyName("urgency");
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "PromisesMade", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Relationships#Relationships.WithProtagonist#RelationshipWithProtagonist.PromisesMade#Promise", b4 =>
                                                {
                                                    b4.Property<bool>("IsFulfilled")
                                                        .HasJsonPropertyName("is_fulfilled");

                                                    b4.Property<string>("PromiseText")
                                                        .HasJsonPropertyName("promise");

                                                    b4.Property<string>("SceneMade")
                                                        .HasJsonPropertyName("scene_made");
                                                });

                                            b3.ComplexCollection(typeof(List<Dictionary<string, object>>), "SharedExperiences", "FableCraft.Infrastructure.Persistence.Entities.CharacterState.CharacterStats#CharacterStats.Relationships#Relationships.WithProtagonist#RelationshipWithProtagonist.SharedExperiences#SharedExperience", b4 =>
                                                {
                                                    b4.Property<string>("Description")
                                                        .HasJsonPropertyName("description");

                                                    b4.Property<string>("EmotionalImpact")
                                                        .HasJsonPropertyName("emotional_impact");

                                                    b4.Property<string>("ExperienceType")
                                                        .HasJsonPropertyName("experience_type");

                                                    b4.Property<string>("SceneReference")
                                                        .HasJsonPropertyName("scene_reference");

                                                    b4.Property<int>("TrustChange")
                                                        .HasJsonPropertyName("trust_change");
                                                });
                                        });
                                });

                            b1.ToJson("CharacterStats");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SceneId");

                    b.HasIndex("SequenceNumber");

                    b.ToTable("CharacterStates");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextualizedChunk")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("KnowledgeGraphNodeId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawChunk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReferenceTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.LorebookEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SceneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("SceneId");

                    b.ToTable("LorebookEntries");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.MainCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId")
                        .IsUnique();

                    b.ToTable("MainCharacter");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.MainCharacterAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("CharacterActions");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdventureId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdventureSummary")
                        .HasColumnType("text");

                    b.Property<bool>("Commited")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NarrativeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventureId");

                    b.HasIndex("SequenceNumber");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.TrackerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("TrackerDefinitions");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Character", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure", null)
                        .WithMany("Characters")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.CharacterState", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Character", "Character")
                        .WithMany("CharacterStates")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Scene", null)
                        .WithMany("CharacterStates")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.LorebookEntry", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure", "Adventure")
                        .WithMany("Lorebook")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Scene", "Scene")
                        .WithMany("Lorebooks")
                        .HasForeignKey("SceneId");

                    b.Navigation("Adventure");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.MainCharacter", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure", null)
                        .WithOne("MainCharacter")
                        .HasForeignKey("FableCraft.Infrastructure.Persistence.Entities.MainCharacter", "AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.MainCharacterAction", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Scene", "Scene")
                        .WithMany("CharacterActions")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Scene", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Adventure", "Adventure")
                        .WithMany("Scenes")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adventure");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Adventure", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Lorebook");

                    b.Navigation("MainCharacter")
                        .IsRequired();

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Character", b =>
                {
                    b.Navigation("CharacterStates");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Scene", b =>
                {
                    b.Navigation("CharacterActions");

                    b.Navigation("CharacterStates");

                    b.Navigation("Lorebooks");
                });
#pragma warning restore 612, 618
        }
    }
}
