namespace FableCraft.Infrastructure.Persistence.Entities.Adventure;

public enum AgentName
{
    WriterAgent,
    SceneTrackerAgent,
    CharacterTrackerAgent,
    MainCharacterTrackerAgent,
    CharacterCrafter,
    PartialProfileCrafter,
    ItemCrafter,
    LoreCrafter,
    LocationCrafter,
    ContextGatherer,
    CharacterPlugin,
    MainCharacterEmulatorAgent,
    InitMainCharacterTrackerAgent,
    CharacterReflectionAgent,
    ExperientialNarratorAgent,
    ClinicalAssessorAgent,
    ChroniclerAgent,
    NarrativeCatalystAgent,
    SimulationPlannerAgent,
    StandaloneSimulationAgent,
    IntentCheckAgent,
    CharacterSimulation,
    SimulationModeratorAgent,
    WorldInfoExtractorAgent,
    EmulationOrchestratorAgent,
    StorySummaryAgent,
    CoLocationAgent,
    ImagePromptAgent,
    ProgressionAgent,
    InventoryTrackerAgent,
    QualityAssuranceAgent
}