// <auto-generated />
using System;
using FableCraft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FableCraft.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029213808_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Character", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StatsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.CharacterAction", b =>
                {
                    b.Property<Guid>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.HasKey("ActionId");

                    b.HasIndex("SceneId");

                    b.ToTable("CharacterActions");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.LorebookEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("EntryId");

                    b.HasIndex("WorldId");

                    b.ToTable("LorebookEntries");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Scene", b =>
                {
                    b.Property<Guid>("SceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NarrativeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NextSceneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousSceneId")
                        .HasColumnType("uuid");

                    b.Property<string>("SceneStateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("SceneId");

                    b.HasIndex("NextSceneId");

                    b.HasIndex("PreviousSceneId");

                    b.HasIndex("WorldId");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.World", b =>
                {
                    b.Property<Guid>("WorldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UniverseBackstory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorldId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.CharacterAction", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Scene", "Scene")
                        .WithMany("CharacterActions")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.LorebookEntry", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Lorebook")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Scene", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Scene", "NextScene")
                        .WithMany()
                        .HasForeignKey("NextSceneId");

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Scene", "PreviousScene")
                        .WithMany()
                        .HasForeignKey("PreviousSceneId");

                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.World", "World")
                        .WithMany("Scenes")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextScene");

                    b.Navigation("PreviousScene");

                    b.Navigation("World");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.World", b =>
                {
                    b.HasOne("FableCraft.Infrastructure.Persistence.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.Scene", b =>
                {
                    b.Navigation("CharacterActions");
                });

            modelBuilder.Entity("FableCraft.Infrastructure.Persistence.Entities.World", b =>
                {
                    b.Navigation("Lorebook");

                    b.Navigation("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
